const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  try {
    const page=await browser.newPage({viewport:{width:1120,height:752}});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.addInitScript(()=>{
      window.sent=[];window.receive=null;
      window.chrome={webview:{postMessage:m=>window.sent.push(m),addEventListener:(_,handler)=>window.receive=handler}};
    });
    await page.goto('file:///'+path.resolve('src/web/app.html').replaceAll('\\','/'));
    const defaults={hasPassword:false,monitors:3,hotkeysOk:true,context:'Desktop'};
    for(const m of fs.readFileSync('src/core.h','utf8').matchAll(/(?:int|bool)\s+(\w+)\s*=\s*(\d+|true|false|'[A-Z]')\s*;/g)) {
      defaults[m[1]]=m[2]==='true'?true:m[2]==='false'?false:m[2][0]==="'"?m[2].charCodeAt(1):Number(m[2]);
    }
    defaults.clock=true;
    defaults.version='1.0.0';   // status field, not a core.h default
    await page.evaluate(s=>window.receive({data:JSON.stringify(s)}),defaults);
    assert.equal(await page.locator('.scene').count(),12);
    await page.locator('nav [data-act="launch"]').click();
    assert(await page.evaluate(()=>window.sent.includes('act:launch')));
    await page.locator('.scene').nth(2).hover();
    assert(await page.evaluate(()=>window.sent.includes('hover:2')));
    await page.locator('[data-page="scenes"] h1').hover();
    await page.evaluate(()=>window.sent=[]);
    await page.locator('.scene').nth(2).hover();
    await page.locator('[data-page="scenes"] h1').hover();
    assert(await page.evaluate(()=>window.sent.includes('hover:2')&&window.sent.includes('hover:-1')));
    for(const tab of ['appearance','behavior','scenes']) {
      await page.locator('[data-tab="'+tab+'"]').click();
      assert.equal(await page.locator('#previewBox').evaluate(x=>x.closest('.page').dataset.page),tab);
      assert(await page.locator('#previewBox').isVisible());
    }
    await page.locator('[data-tab="behavior"]').click();
    assert.equal(await page.locator('#behRun .row').filter({hasText:'Accidental wake protection'}).count(),1);
    await page.locator('#behRun .row').filter({hasText:'Wake with keyboard'}).locator('.sw').click();
    assert(await page.evaluate(()=>window.sent.includes('set:wakeKeyboard:0')));
    const wakeSlider=page.locator('#behRun .row').filter({hasText:'Mouse wake distance'}).locator('input');
    await wakeSlider.fill('73');
    assert(await page.evaluate(()=>window.sent.includes('set:wakeMouseThreshold:73')));
    await page.evaluate(()=>window.originalScene=document.querySelector('.scene'));
    await page.evaluate(s=>window.receive({data:JSON.stringify(s)}),defaults);
    assert(await page.evaluate(()=>window.originalScene===document.querySelector('.scene')),'state update preserves decoded images');
    await page.locator('#q').fill('clock');
    assert.equal(await page.locator('#results button').count(),1);
    await page.locator('#results button').click();
    assert(await page.locator('[data-page="appearance"]').isVisible());
    await page.getByRole('button',{name:'Choose clock…'}).click();
    assert(await page.locator('#clockLive').isVisible());
    await page.locator('#cstyles button').nth(1).click();
    assert(await page.locator('#modal').innerText().then(x=>x.includes('Typography')));
    const clockFrame='data:image/png;base64,'+'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=';
    await page.evaluate(url=>window.receive({data:'frame:'+url}),clockFrame);
    await page.waitForFunction(()=>window.sent.includes('frameReady:1'));
    await page.locator('#modal').evaluate(el=>el.scrollTop=0);
    await page.screenshot({path:'build/clock-popup.png'});
    await page.getByRole('button',{name:'Done',exact:true}).click();
    await page.locator('#q').fill('<img src=x onerror="window.injected=true">');
    assert(await page.locator('#results').innerText().then(x=>x.includes('Nothing found')));
    assert.equal(await page.locator('#results img').count(),0,'search input stays text');
    await page.locator('#q').fill('');
    await page.locator('[data-tab="system"]').click();
    await page.getByRole('button',{name:'Disable',exact:true}).first().click();
    assert(await page.evaluate(()=>window.sent.includes('set:hotkeyToggleKey:0')));
    await page.locator('[data-tab="scenes"]').click();
    await page.locator('#btnPresets').click();
    await page.evaluate(()=>window.receive({data:'presets:<b>Hostile preset</b>'}));
    assert.equal(await page.locator('.pitem b b').count(),0,'preset names stay text');
    await page.locator('#pname').fill('Night glass');await page.locator('#psave').click();
    assert(await page.evaluate(()=>window.sent.includes('act:presetSave:Night glass')));
    await page.locator('#pclose').click();
    for(const tab of ['scenes','behavior','appearance','security','performance','system','credits']) {
      await page.locator(`[data-tab="${tab}"]`).click();
      assert(await page.locator(`[data-page="${tab}"]`).isVisible(),`${tab} page shows`);
      assert.equal(await page.locator('.studio-stamp').count(),0,'release has no development watermark');
    }
    assert.equal(await page.locator('[data-tab="performance"] svg').count(),1);
    // Cursor section: style switch, file request, and the host's picture applied as the page cursor.
    await page.locator('[data-tab="appearance"]').click();
    await page.getByRole('button',{name:'Orbit',exact:true}).click();
    assert(await page.evaluate(()=>window.sent.includes('set:cursorStyle:1')));
    assert.equal(await page.locator('#appCursor button',{hasText:'Violet'}).count(),1,'Orbit shows its colours');
    assert.equal(await page.locator('#appCursor .tint').count(),6,'Orbit colours use decorative dots, not HTML in labels');
    assert.equal(await page.locator('#appCursor').innerText().then(x=>x.includes('<i class=')),false,'Orbit colour labels do not expose markup');
    const dot='data:image/png;base64,'+'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=';
    await page.evaluate(u=>window.receive({data:'cursor:'+JSON.stringify({on:true,url1:u,url2:u,x:14,y:14,size:28,trail:true,color:'#97f2cf'})}),dot);
    assert((await page.evaluate(()=>getComputedStyle(document.querySelector('.card')).cursor)).includes('data:image/png'),'host pointer becomes the page cursor');
    assert.equal(await page.locator('.pointerTile img').count(),1);
    await page.mouse.move(300,300); await page.mouse.move(420,340,{steps:6}); await page.mouse.down(); await page.mouse.up();
    await page.getByRole('button',{name:'Your file',exact:true}).click();
    assert(await page.evaluate(()=>window.sent.includes('act:cursorFile')),'choosing "Your file" without one opens the picker');
    await page.evaluate(()=>window.receive({data:'cursor:{"on":false}'}));
    assert.equal(await page.locator('#pointerStyle').textContent(),'');
    // Version comes from the build; the About pill and sidebar show it.
    await page.locator('[data-tab="system"]').click();
    assert.equal(await page.locator('#verPill').innerText(),'v1.0.0');
    assert.equal(await page.locator('#navVer').innerText(),'1.0.0');
    assert.equal(await page.locator('#stBody').innerText(),'v1.0.0','sidebar status shows the version, not a dash');
    // Start with Windows reflects the registry truth and sends an act, not a set.
    await page.locator('#sysStartup .row').filter({hasText:'Start with Windows'}).locator('.sw').click();
    assert(await page.evaluate(()=>window.sent.includes('act:autostart:1')));
    assert(await page.locator('#sysStartup .row').filter({hasText:'Open the window on start'}).evaluate(r=>r.classList.contains('off')),'the show-window row is dimmed until autostart is on');
    // Check for updates: checking spinner, an available release with a download button, and up-to-date.
    await page.locator('#btnUpdate').click();
    assert(await page.evaluate(()=>window.sent.includes('act:checkUpdate')));
    await page.evaluate(()=>window.receive({data:'update:{"state":"checking"}'}));
    assert(await page.locator('.upd-spin').isVisible());
    await page.evaluate(()=>window.receive({data:'update:'+JSON.stringify({state:'available',latest:'v1.2.0',current:'1.0.0',canOpen:true,notes:'Fixes & <polish>'})}));
    assert(await page.locator('#modal').innerText().then(x=>x.includes('1.2.0')&&x.includes('<polish>')),'release notes are shown and HTML-escaped');
    await page.getByRole('button',{name:'Download update'}).click();
    assert(await page.evaluate(()=>window.sent.includes('act:openUpdate')));
    await page.evaluate(()=>window.receive({data:'update:{"state":"current"}'}));
    assert(await page.locator('#modal').innerText().then(x=>x.toLowerCase().includes('up to date')));
    await page.keyboard.press('Escape');
    await page.evaluate(()=>window.receive({data:'update:'+JSON.stringify({state:'available',latest:'<img src=x onerror="window.injected=true">',canOpen:false,notes:'<script>bad</script>'})}));
    assert.equal(await page.locator('#modal img, #modal script').count(),0,'all remote update text is escaped');
    assert(!(await page.evaluate(()=>window.injected)));
    await page.keyboard.press('Escape');
    // Native authorization must finish before a sensitive action is sent.
    await page.locator('[data-tab="security"]').click();
    await page.locator('#btnSetPw').click();
    assert.notEqual(await page.locator('#p1Eye').evaluate(el=>getComputedStyle(el).color),'rgb(0, 0, 0)','password eye is visible on dark input');
    await page.locator('#p1Eye').click();
    assert.equal(await page.locator('#p1').getAttribute('type'),'text','password eye reveals input');
    assert.equal(await page.locator('#p1Eye').getAttribute('aria-pressed'),'true');
    await page.locator('#p1Eye').click();
    assert.equal(await page.locator('#p1').getAttribute('type'),'password','password eye hides input again');
    assert.equal(await page.locator('#p1').getAttribute('maxlength'),'6','new password is capped at 6 characters');
    await page.locator('#p1').fill('abc'); await page.locator('#p2').fill('abc'); await page.locator('#pOk').click();
    assert((await page.locator('#pErr').innerText()).includes('4'));
    await page.keyboard.press('Escape');
    await page.evaluate(s=>{window.receive({data:JSON.stringify({...s,hasPassword:true,lockEnabled:true})});window.sent=[];},defaults);
    await page.locator('[data-act="clearPassword"]').click();
    assert(await page.locator('#currentPassword').isVisible());
    assert(!(await page.evaluate(()=>window.sent.includes('act:clearPassword'))));
    await page.locator('#currentPassword').fill('old password'); await page.locator('#authOk').click();
    assert.equal(await page.locator('#currentPassword').inputValue(),'');
    assert(await page.locator('#authOk').isDisabled());
    await page.evaluate(()=>window.receive({data:'authError:Incorrect password'}));
    assert.equal(await page.locator('#authErr').innerText(),'Incorrect password');
    assert(!(await page.locator('#authOk').isDisabled()));
    await page.locator('#currentPassword').fill('old password'); await page.locator('#authOk').click();
    await page.evaluate(()=>window.receive({data:'authorized'}));
    assert.equal(await page.evaluate(()=>window.sent.filter(m=>m==='act:clearPassword').length),1);
    await page.locator('#btnSetPw').click();
    await page.locator('#authCancel').click();
    await page.evaluate(()=>window.receive({data:'authorized'}));
    assert(!(await page.locator('#p1').count()),'late authorization after cancel does not reopen a dialog');
    await page.locator('#btnSetPw').click();
    await page.locator('#currentPassword').fill('old password'); await page.locator('#authOk').click();
    await page.evaluate(()=>window.receive({data:'authorized'}));
    await page.locator('#p1').fill('abc12'); await page.locator('#p2').fill('abc12'); await page.locator('#pOk').click();
    assert(await page.evaluate(()=>window.sent.includes('pw:abc12')));
    await page.evaluate(s=>window.receive({data:JSON.stringify({...s,securityError:true})}),defaults);
    assert(await page.locator('#btnSetPw').isDisabled());
    assert(await page.locator('[data-act="clearPassword"]').isDisabled());
    assert((await page.locator('#pwHint').innerText()).includes('Fullscreen is disabled'));
    await page.evaluate(s=>window.receive({data:JSON.stringify(s)}),defaults);
    // Library refresh buttons re-scan on the host.
    await page.locator('[data-tab="scenes"]').click();
    await page.locator('[data-page="scenes"] [data-act="refreshLibrary"]').click();
    assert(await page.evaluate(()=>window.sent.includes('act:refreshLibrary')));
    await page.locator('#btnPresets').click();
    await page.evaluate(()=>window.sent=[]);
    await page.locator('#prefresh').click();
    assert(await page.evaluate(()=>window.sent.includes('act:presets')));
    await page.locator('#pclose').click();
    await page.goto('file:///'+path.resolve('src/web/lock.html').replaceAll('\\','/'));
    await page.evaluate(()=>window.receive({data:'theme:{"palette":3,"roundness":18}'}));
    await page.evaluate(()=>window.receive({data:'reveal'}));
    assert(await page.locator('#eye').isVisible());
    assert.equal(await page.locator('#go').count(),0,'no submit button');
    assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('#card')).cursor),'none','no pointer over the prompt');
    assert.equal(await page.locator('#pw').getAttribute('type'),'password');
    const eye=await page.locator('#eye').boundingBox();
    await page.mouse.click(eye.x+eye.width/2,eye.y+eye.height/2);
    assert.equal(await page.locator('#pw').getAttribute('type'),'password','the mouse does nothing here');
    assert(await page.evaluate(()=>document.activeElement.id==='pw'),'focus stays in the password field');
    await page.keyboard.press('Alt+F8');
    assert.equal(await page.locator('#pw').getAttribute('type'),'text');
    await page.keyboard.press('Alt+F8');
    assert.equal(await page.locator('#pw').getAttribute('type'),'password');
    assert.equal(await page.locator('#eye').evaluate(el=>getComputedStyle(el).color),'rgb(207, 131, 255)');
    await page.locator('#pw').fill('temporary');
    await page.waitForTimeout(5300);
    assert(await page.locator('#card').evaluate(x=>x.classList.contains('away')&&x.inert));
    assert.equal(await page.locator('#pw').inputValue(),'');
    await page.keyboard.press('a');
    assert(await page.locator('#card').evaluate(x=>!x.classList.contains('away')&&!x.inert));
    await page.screenshot({path:'build/lock-ready.png'});
    await page.waitForTimeout(5300);
    assert(!(await page.evaluate(()=>window.sent.includes('rest'))));
    await page.waitForTimeout(10100);
    assert(await page.evaluate(()=>window.sent.includes('rest')));
    await page.evaluate(()=>window.receive({data:'reveal'}));
    assert(await page.locator('#card').evaluate(x=>!x.inert));
    // Known length: input stops at the last character and submits by itself, right away.
    await page.evaluate(()=>{window.sent=[];window.receive({data:'theme:{"palette":3,"roundness":18,"length":6,"hideCursor":false}'});window.receive({data:'reveal'});});
    assert.equal(await page.locator('#slots i').count(),6);
    await page.keyboard.type('abcdefgh');
    assert.deepEqual(await page.evaluate(()=>window.sent.filter(m=>m.startsWith('try:'))),['try:abcdef']);
    assert.equal(await page.locator('#pw').inputValue(),'abcdef');
    assert.equal(await page.locator('#slots i.on').count(),6);
    await page.evaluate(()=>window.receive({data:'wrong:1'}));
    assert.equal(await page.locator('#pw').inputValue(),'');
    assert(await page.locator('#msg').innerText().then(x=>x.includes('attempt 1')));
    await page.keyboard.type('xyz'); await page.keyboard.press('Enter');
    assert.equal(await page.evaluate(()=>window.sent.filter(m=>m.startsWith('try:')).length),1,'a short entry is never sent');
    await page.keyboard.type('uvw');
    assert.deepEqual(await page.evaluate(()=>window.sent.filter(m=>m.startsWith('try:'))),['try:abcdef','try:xyzuvw']);
    await page.evaluate(()=>window.receive({data:'wrong:2'}));
    // Once the prompt has stepped aside, the pointer follows Hide cursor (off in this theme).
    await page.waitForTimeout(5300);
    assert.equal(await page.evaluate(()=>getComputedStyle(document.body).cursor),'default');
    await page.keyboard.press('a');
    assert.equal(await page.evaluate(()=>getComputedStyle(document.body).cursor),'none');
    assert.deepEqual(errors,[]);
    console.log('PASS: persistent scene images, grouped search, clock popup, hotkey disable, named preset, every tab switches, sidebar version, cursor section, mouse-proof lock, length-based auto unlock, whole password card idle/wake; no JS errors');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
