const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try {
  const page=await browser.newPage({viewport:{width:1120,height:752}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{window.sent=[];window.chrome={webview:{postMessage:m=>sent.push(m),addEventListener:(_,h)=>window.receive=h}};});
  await page.route('https://hibernation-media.local/**',r=>r.fulfill({contentType:'video/mp4',body:fs.readFileSync('build/test-media/test.mp4')}));
  await page.goto('file:///'+path.resolve('src/web/app.html').replaceAll('\\','/'));
  const defaults={monitors:1,context:'Desktop',hotkeysOk:true};
  for(const m of fs.readFileSync('src/core.h','utf8').matchAll(/(?:int|bool)\s+(\w+)\s*=\s*(\d+|true|false|'[A-Z]')\s*;/g)) defaults[m[1]]=m[2]==='true'?true:m[2]==='false'?false:m[2][0]==="'"?m[2].charCodeAt(1):Number(m[2]);
  await page.evaluate(d=>window.receive({data:JSON.stringify(d)}),defaults);
  await page.locator('[data-tab="performance"]').click();
  await page.getByRole('button',{name:'Ultra economy',exact:true}).click();
  assert(await page.evaluate(()=>sent.includes('set:fps:15')&&sent.includes('set:quality:100')&&sent.includes('set:deepRest:1')&&sent.includes('set:previewFps:10')&&sent.includes('set:previewWidth:800')));
  assert.equal(await page.getByText('Fullscreen resolution',{exact:true}).count(),1);
  assert.equal(await page.getByText('Native',{exact:true}).count(),1);
  assert.equal(await page.locator('[data-tab="performance"] svg').count(),1);
  assert.equal(await page.locator('#previewBox').evaluate(x=>x.closest('.page').dataset.page),'performance');
  await page.screenshot({path:'build/performance-settings.png'});
  await page.locator('#debugControls .row').filter({hasText:'Enable diagnostics'}).locator('.sw').click();
  assert(await page.evaluate(()=>sent.includes('set:debugEnabled:1')));
  await page.evaluate(()=>receive({data:'stats:'+JSON.stringify({renderer:'D3D11 hardware',fps:29.81,cap:30,quality:50,width:960,height:540,appCpu:1.25,nativeCpu:.5,systemCpu:7,appMb:220,nativeMb:35,frameMs:.5,peakMs:1.2,gpuMs:2.8,totalFrames:100,lateFrames:2,baselineCpu:2,cpuDelta:-.75,memoryDelta:-5,systemDelta:-1})}));
  assert((await page.locator('#debugReadout').innerText()).includes('29.81 measured FPS'));
  assert.equal(await page.locator('#perfGraph polyline').count(),2);
  await page.getByRole('button',{name:'Save baseline',exact:true}).click();
  assert(await page.evaluate(()=>sent.includes('act:debugBaseline')));
  await page.locator('[data-tab="scenes"]').click();
  await page.locator('#addMedia').click();
  assert(await page.getByRole('button',{name:'Choose file…',exact:true}).isDisabled());
  await page.locator('#mediaName').fill('My animation');
  await page.getByRole('button',{name:'Choose file…',exact:true}).click();
  assert(await page.evaluate(()=>sent.includes('mediaAdd:My animation')));
  const item={id:1,name:'<b>My animation</b>',file:'1.mp4',source:'D:\\original.mp4',missing:false};
  await page.evaluate(item=>receive({data:'library:'+JSON.stringify({folder:'Test library',items:[item]})}),item);
  assert.equal(await page.locator('#mediaGrid b').count(),0,'names stay text');
  await page.locator('#mediaGrid button').click();
  await page.locator('#previewBox').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelector('#mediaPreviewVideo').currentTime>0);
  await page.locator('[data-tab="credits"]').click();
  await page.waitForFunction(()=>document.querySelector('#mediaPreviewVideo').paused);
  await page.locator('[data-tab="scenes"]').click();
  await page.locator('#mediaGrid button').click({button:'right'});
  await page.getByRole('button',{name:'Rename',exact:true}).click();
  await page.locator('#mediaName').fill('Renamed');await page.getByRole('button',{name:'Save name',exact:true}).click();
  assert(await page.evaluate(()=>sent.includes('mediaRename:1:Renamed')));
  await page.locator('#mediaGrid button').click({button:'right'});
  await page.getByRole('button',{name:'Change path / replace file',exact:true}).click();
  assert(await page.evaluate(()=>sent.includes('mediaReplace:1')));
  await page.locator('#mediaGrid button').click({button:'right'});
  await page.getByRole('button',{name:'Delete library copy',exact:true}).click();
  assert(!(await page.evaluate(()=>sent.includes('mediaDelete:1'))));
  await page.getByRole('button',{name:'Confirm delete',exact:true}).click();
  assert(await page.evaluate(()=>sent.includes('mediaDelete:1')));
  await page.locator('.scene').first().click();
  assert(await page.evaluate(()=>sent.includes('set:mediaId:0')));
  assert.deepEqual(errors,[]);
  console.log('PASS: profiles, diagnostics, baseline, required media name, safe labels, video preview/play/pause, rename, replace and confirmed deletion.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
